{%- set component_name = values.product_name | lower | replace(' ', '-') -%}
{%- set docs_dir = values.docs_directory | default('docs') -%}
site_name: "${{ values.product_name }}"

plugins:
  - techdocs-core

nav:
  - Home: index.md
